version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: frontend-app
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: ngnix-server
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    ports:
      - 5555:80
